-- 111 leads from oc-leads.csv
INSERT INTO public.leads (business_name, phone, city, website, status, list_name)
VALUES
  ('GG landscape enterprises Inc.', '+17143265436', 'Anaheim', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('Ricardo Landscaping', NULL, 'Fullerton', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('U C Landscape', '+17147209741', 'Fullerton', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('Orange Landscaping Services', '+17144460852', 'Fullerton', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('Planet Green Landscaping', '+17144497879', 'Fullerton', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('Rosales Landscaping', '+17149917357', 'Anaheim', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('Martin Gonzalez - Landscape & Maintenance', '+17148845522', 'Santa Ana', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('Bright Vista Landscape Inc.', '+17148529506', 'Santa Ana', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('Vega’s Landscaping & Tree Service - Orange County, CA', '+16574807211', 'Fullerton', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('Southwest Landscape Inc', '+17145451084', 'Santa Ana', 'http://www.southwestlandscape.org/', 'new', 'OC Landscapers - Batch 1'),
  ('Phoenix Landscaping Inc', '+17145721410', 'Fullerton', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('Superior Landscape Services', '+17149724702', 'Anaheim', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('Advanced Patio & Landscape', '+17143307811', 'Huntington Beach', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('Terrascapes', '+17149625450', 'Huntington Beach', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('OC Pro Scape Anaheim - Landscaping Services & Sprinkler Installation', '+17144205145', 'Anaheim', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('SUAZO LANDSCAPE INC', '+19492053983', 'Anaheim', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('Action Landscape Services, Inc.', '+19517367776', 'Anaheim', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('ALDIA LANDSCAPE', '+17143518886', 'Huntington Beach', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('U P Landscape Maintenance Inc', '+19495511323', 'Irvine', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('JC & Co Land Art Studio', '+19493023858', 'Newport Beach', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('California Landscape Inc', '+19496738971', 'Newport Beach', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('Native Landscaping', '+17143499913', 'Newport Beach', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('landscaping anaheim ca', '+17144106987', 'Anaheim', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('RAA Landscape & Maintenance', '+17143363130', 'Fullerton', NULL, 'new', 'OC Landscapers - Batch 1'),
  ('CG Landscape', '+17145355640', 'Anaheim', 'https://cglandscape.net/', 'new', 'OC Landscapers - Batch 1'),
  ('Brothers Landscape Services', '+17146834173', 'Anaheim', 'http://brotherslandscapeoc.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Ultimate Landscaping Management', '+17145029711', 'Anaheim', 'http://www.ulmci.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Aquagreen Pool & Landscape - Orange county', '+18589522207', 'Irvine', 'http://www.aquagreenlandscape.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Orozco''s Lawncare Solutions', '+19492832320', 'Orange', 'https://orozcoslawncaresolutions.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Mark Scott Associates', '+19498521727', 'Newport Beach', 'http://markscottassociates.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Caliscapes OC', '+17143484808', 'Orange', 'http://www.caliscapesoc.com/', 'new', 'OC Landscapers - Batch 1'),
  ('M.W. Landscape', '+17146690201', 'Tustin', 'http://mwlandscape.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Landscape by Hiro', '+17149680601', 'Huntington Beach', 'http://www.landscapebyhiro.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Mariposa Landscapes, Inc. | Santa Ana', '+18007949458', 'Santa Ana', 'http://mariposa-ca.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Silverwood Landscape Construction', '+17144276134', 'Santa Ana', 'http://silverwoodlandscapeconstruction.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Perez Tree Service & Landscaping', '+17149321527', 'Santa Ana', 'https://perez-landscaping-services.com/', 'new', 'OC Landscapers - Batch 1'),
  ('OC Landscaping and Hauling', '+19493444490', 'Trabuco Canyon', 'https://oclandscapingandhauling.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Vargas Landscaping', '+17144205566', 'Fullerton', 'https://fullertontreeexpert.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Premier Landscape Inc', '+17148400827', 'Huntington Beach', 'https://premierlandscapeca.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Wilson Greens Turf', '+15627565524', 'Huntington Beach', 'https://www.wilsongreensturf.com/', 'new', 'OC Landscapers - Batch 1'),
  ('A Growing Concern Landscape', '+17148435137', 'Huntington Beach', 'http://www.growingconcern.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Lifetime Outdoor Living', '+19499190339', 'Irvine', 'https://lifetimeoutdoorliving.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Landmark Custom Landscape', '+17146698882', 'Irvine', 'https://www.landmarkcustomlandscape.com/', 'new', 'OC Landscapers - Batch 1'),
  ('HavenHub', '+18555894909', 'Newport Beach', 'https://havenhub.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Coastal Designs Landscaping', '+19498182396', 'Newport Beach', 'https://www.coastaldesignslandscaping.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Pacific Coast Landscaping', '+17147734865', 'Fullerton', 'http://www.pacificcoastlandscaping.com/', 'new', 'OC Landscapers - Batch 1'),
  ('OC West Landscape', '+19499396639', 'Irvine', 'http://ocwest.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Five Star Turf', '+17145433000', 'Irvine', 'http://fivestarturfcommercial.com/', 'new', 'OC Landscapers - Batch 1'),
  ('AMS Landscape Design Studios, Inc.', '+19498516557', 'Newport Beach', 'http://www.amslandscapedesign.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Tarantino Landscape Inc.', '+19492267215', 'Santa Ana', 'http://www.tarantinolandscape.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Conscious Environments, Inc.', '+17148824750', 'Yorba Linda', 'http://conscious-environments.com/', 'new', 'OC Landscapers - Batch 1'),
  ('California Landcare', '+17148501028', 'Santa Ana', 'https://californialandcare.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Heavenly''s Lawn Care', '+19493570965', 'Costa Mesa', 'https://www.heavenlyslawncareoc.com/', 'new', 'OC Landscapers - Batch 1'),
  ('The Landscape Expert', '+17148553479', 'Anaheim', 'https://www.thelandscapingexpert.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Romero''s Gardening INC.', '+17143817085', 'Santa Ana', 'https://romerosgardening.contractors/', 'new', 'OC Landscapers - Batch 1'),
  ('SiteOne Landscape Supply', '+17142859092', 'Santa Ana', 'https://www.siteone.com/en/store/388', 'new', 'OC Landscapers - Batch 1'),
  ('Better Green Scapess', '+19497748181', 'Santa Ana', 'http://bettergreenscapes.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Merchants Landscape Services', '+18006454881', 'Santa Ana', 'http://www.merchantslandscape.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Earthco Landscape', '+17145710455', 'Santa Ana', 'http://www.earthcolandscape.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Costa Verde Landscape Inc', '+17146689900', 'Santa Ana', 'http://www.costaverdelandscape.com/', 'new', 'OC Landscapers - Batch 1'),
  ('GL3 Luxury Lighting', '+16576511172', 'Huntington Beach', 'http://www.gl3luxurylighting.com/', 'new', 'OC Landscapers - Batch 1'),
  ('W BROTHERS LANDSCAPE, Inc.', '+18559276757', 'Orange', 'http://wbroslandscape.com/', 'new', 'OC Landscapers - Batch 1'),
  ('TRU Landscape Services', '+18664871359', 'Orange', 'http://www.trulandscape.com/', 'new', 'OC Landscapers - Batch 1'),
  ('KC Landscape Inc.', '+17144479679', 'Fullerton', 'http://kclandscapeinc.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Plant Nerd Inc', '+17148424100', 'Huntington Beach', 'http://www.theplantnerd.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Royal Outdoor Design', '+19493333442', 'Huntington Beach', 'http://royaloutdoordesign.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Green Origin Landscape Designs', '+19496498149', 'Huntington Beach', 'http://www.greenorigindesigns.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Aquaterra Pool & Landscape', '+19493866217', 'Santa Ana', 'http://aquaterralandscape.com/', 'new', 'OC Landscapers - Batch 1'),
  ('4Ever Green Landscape', '+17147238222', 'Huntington Beach', 'http://landscape4ever.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Park West', '+19495468300', 'Santa Ana', 'http://www.parkwestinc.com/', 'new', 'OC Landscapers - Batch 1'),
  ('OC Sprinkler Doctor', '+17148189644', 'Fullerton', 'http://sprinklerdoctoroc.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Pacific Terrain Landscape Maintenance', '+19496607085', 'Irvine', 'http://pacificterrain.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Best Landscape Designers Fullerton', '+17143644847', 'Fullerton', 'http://bestlandscapedesignersfullerton.services/', 'new', 'OC Landscapers - Batch 1'),
  ('Simple Outdoor Living', '+17143885878', 'Irvine', 'http://www.simpleoutdoorliving.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Luis Hernandez Landscaping', '+19495143624', 'Anaheim', 'http://lhernandezlandscaping.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Yard Design', '+19494013370', 'Irvine', 'https://www.yarddes.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Black Diamond Paver Stones & Landscape, Inc.', '+19493524759', 'Irvine', 'https://blackdiamondlandscape.com/orange-county/?utm_source=Google&utm_medium=GMB&utm_campaign=OrangeCountyIrvine', 'new', 'OC Landscapers - Batch 1'),
  ('Coastal Greenscapes Artificial Turf', '+17142679207', 'Anaheim', 'https://scturf.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Greener Gardens', '+17143625861', 'Huntington Beach', 'https://greenergardenslandscaping.com/contact-us/', 'new', 'OC Landscapers - Batch 1'),
  ('OC Landscape Maintenance', '+17149312733', 'Santa Ana', 'https://oclandscaper.com/', 'new', 'OC Landscapers - Batch 1'),
  ('West Hills Masonry', '+17145195009', 'Irvine', 'https://www.westhillsmasonry.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Aragon: Orange County Lawn Care & Landscaping Company', '+19499030234', 'Costa Mesa', 'https://orangecountylawncare.net/', 'new', 'OC Landscapers - Batch 1'),
  ('Papaya Construction Group', '+19494000032', 'Irvine', 'https://papayaconstruction.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Fullerton Landscapers', '+16574410348', 'Fullerton', 'https://fullertonlandscapers.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Cultivate OC- Landscape & Maintenance', '+18182942477', 'Newport Beach', 'https://cultivateworld.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Greenplace Inc', '+17143997718', 'Costa Mesa', 'https://greenplaceusa.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Signature Landscape', '+19497558636', 'Mission Viejo', 'https://www.signaturelandscape.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Richard Diaz Landscape', '+17146732643', 'Orange', 'https://richarddiazlandscaping.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Landscape Design by Armstrong', '+19496449510', 'Newport Beach', 'https://www.armstronggarden.com/armstrong-garden-centers-newport-beach', 'new', 'OC Landscapers - Batch 1'),
  ('Irvine Landscapers', '+19492675564', 'Irvine', 'https://irvinelandscapers.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Tavera''s Custom Landscape', '+17143964552', 'Orange', 'https://taverascustomlandscape.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Williams Landscape Construction', '+17147903994', 'Anaheim', 'https://www.williamslandscapeconstruction.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Marina Landscape - Anaheim', '+17149396600', 'Anaheim', 'https://www.marinaco.com/contact-us/locations/', 'new', 'OC Landscapers - Batch 1'),
  ('Urban Landscape', '+19494337428', 'Newport Beach', 'https://www.urbanlandscape.com/?utm_source=google&utm_medium=organic&utm_campaign=google_business_profile', 'new', 'OC Landscapers - Batch 1'),
  ('Flawless Grass', '+19492035603', 'Newport Beach', 'https://flawlessgrass.com/contact-us/', 'new', 'OC Landscapers - Batch 1'),
  ('TruGreen Lawn Care', '+18334185004', 'Anaheim', 'https://www.trugreen.com/local-lawn-care/california/anaheim/?utm_source=gmb&utm_channel=organic', 'new', 'OC Landscapers - Batch 1'),
  ('Paradise Designs Inc.', '+19494982155', 'San Clemente', 'https://www.paradisedesigns-inc.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Morales Landscape Management', '+17148046616', 'Santa Ana', 'https://moraleslandscapes.com/', 'new', 'OC Landscapers - Batch 1'),
  ('All Seasons Landscape and Maint. Inc.', '+17145266038', 'Fullerton', 'https://allseasonslandscapeandmaint.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Nieves Landscape', '+17146413071', 'Santa Ana', 'https://www.nieveslandscape.com/', 'new', 'OC Landscapers - Batch 1'),
  ('BrightView Landscapes', '+17145467843', 'Anaheim', 'https://www.brightview.com/local/anaheim-ca-landscape-services', 'new', 'OC Landscapers - Batch 1'),
  ('Southwest Boulder & Stone', '+17148821010', 'Fullerton', 'https://www.southwestboulder.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Lawn Master OC', '+17149705296', 'Fullerton', 'https://lawnmasteroc.com/', 'new', 'OC Landscapers - Batch 1'),
  ('BriteTurf', '+18882787772', 'Orange', 'https://briteturf.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Kodee Landscaping', '+17149296468', 'Santa Ana', 'https://www.kodeelandscaping.com/', 'new', 'OC Landscapers - Batch 1'),
  ('TurFresh', '+18554448873', 'Santa Ana', 'https://www.turfresh.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Reynaldo Landscape Inc.', '+17146566096', 'Fullerton', 'https://www.reynaldolandscapeinc.com/', 'new', 'OC Landscapers - Batch 1'),
  ('DM Landscape and Maintenance', '+19492310753', 'Anaheim', 'https://dmlandscapedesign.co/', 'new', 'OC Landscapers - Batch 1'),
  ('I Jimenez Landscape', '+17148631554', 'Santa Ana', 'https://ijimenezlandscape.com/contact/', 'new', 'OC Landscapers - Batch 1'),
  ('Pacific Breeze Building Solutions', '+17143790744', 'Huntington Beach', 'https://pbbuildingsolutions.com/', 'new', 'OC Landscapers - Batch 1'),
  ('Grizzly Outdoor', '+19498944800', 'Anaheim', 'https://grizzlyoutdoor.com/', 'new', 'OC Landscapers - Batch 1');
